[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Tim Harder <radhermit@gmail.com>"]
edition = "2021"
rust-version = "1.74"

[profile.release-strip]
inherits = "release"
strip = "symbols"
lto = "thin"
codegen-units = 1
