include::include/header.adoc[]

== Name

bite-redmine-search - search issues

== Synopsis

*bite redmine <search|s>* [<options>] [<terms>]::
    Query and output issues.

*bite redmine <search|s>* [-h|--help]::
    Output help information.

== Description

Search issues.

include::include/global-options.adoc[]

== Search options

*-b, --browser*::
    Open in a browser.
+
This functionality uses `xdg-open` to open URLs.

*-n, --dry-run*::
    Skip service interaction.

*--json*::
    Output in JSON format.

*--from <path>*::
    Read search attributes from a template.
+
Template files use the TOML format and generally map long option names to values.
+
Explicitly specified options override corresponding template values.

*--to <path>*::
    Write search attributes to a template.
+
Combining with --dry-run allows creating templates without service interaction.

== Query options

*-f, --fields <field[,...]>*::
    Restrict the data fields returned by the query.
+
By default, only the id and subject fields are returned. This can be altered by
specifying a custom list of comma-separated field while will change the output
format to a space-separated list of the field values.
+
.Possible values:
- *assignee*: user the issue is assigned to
- *author*: user who created the issue
- *closed*: time when the issue was closed
- *created*: time when the issue was created
- *id*: issue ID
- *priority*: issue priority
- *status*: issue status
- *subject*: issue subject
- *tracker*: issue type
- *updated*: time when the issue was last updated

*-l, --limit <value>*::
    Limit the number of results.
+
If the value is higher than the maximum limit that value is used instead and if
the limit is set to zero, the default limit is used. Note that the maximum and
default limits are generally not equal, with most instances using 100 and 25,
respectively.

*-o, --order <field[,...]>*::
    Order the query results.
+
Fields can be prefixed with `-` or `+` to sort in descending or ascending
order, respectively. Unprefixed fields use ascending order.
+
Multiple fields can be specifying in a comma-separated list which sort the
results by each field in order.
+
If an invalid sorting request is made, the default ordering will be used.
+
.Possible values:
- *assignee*: user the issue is assigned to
- *author*: user who created the issue
- *closed*: time when the issue was closed
- *created*: time when the issue was created
- *id*: issue ID
- *priority*: issue priority
- *status*: issue status
- *subject*: issue subject
- *tracker*: issue type
- *updated*: time when the issue was last updated

== Attribute options

*-a, --assignee [<bool>]*::
    Restrict by assignee status.
+
With no argument, all matches with assignees are returned. If the value is
`true` or `false`, all matches with or without assignees are returned,
respectively.
+
.Search for assigned ruby issues:
 bite redmine -c ruby search --assignee
+
.Search for unassigned ruby issues:
 bite redmine -c ruby search --assignee false

*--attachments [<value>[,...]]*::
    Restrict by attachments.
+
With no argument, all matches with attachments are returned. If the
value is `true` or `false`, all matches with or without attachments
are returned, respectively.
+
Regular string values search for matching substrings in an
attachment's file name.
+
Multiple values can be specified in a comma-separated list and will
match if all of the specified values match.
+
.Search for ruby issues with attachments:
 bite redmine -c ruby search --attachments
+
.Search for ruby issues without attachments:
 bite redmine -c ruby search --attachments false
+
.Search for ruby issues with file names containing `test`:
 bite redmine -c ruby search --attachments test
+
.Search for ruby issues with file names containing `test` and `log`:
 bite redmine -c ruby search --attachments test,log

*-B, --blocks [<ID>[,...]]*::
    Restrict by blockers.
+
With no argument, all blocking matches are returned. If the value is `true` or
`false`, all blocking and non-blocking matches are returned, respectively.
+
.Search for ruby issue blockers:
 bite redmine -c ruby search --blocks
+
.Search for non-blocking ruby issues:
 bite redmine -c ruby search --blocks false
+
Regular values search for matching blockers and multiple values can be
specified in a comma-separated list, matching if any of the specified blockers
match.
+
.Search for ruby issues blocking issue #10:
 bite redmine -c ruby search --blocks 10
+
.Search for ruby issues blocking issues #10 or #11:
 bite redmine -c ruby search --blocks 10,11
+
Values are taken from standard input when `-`.

*-D, --blocked [<ID>[,...]]*::
    Restrict by dependencies.
+
With no argument, all matches with dependencies are returned. If the value is
`true` or `false`, all matches with or without dependencies are returned,
respectively.
+
.Search for ruby issues with dependencies:
 bite redmine -c ruby search --blocked
+
.Search for ruby issues without dependencies:
 bite redmine -c ruby search --blocked false
+
Regular values search for matching dependencies and multiple values can be
specified in a comma-separated list, matching if any of the specified
dependencies match.
+
.Search for ruby issues blocked on issue #10:
 bite redmine -c ruby search --blocked 10
+
.Search for ruby issues blocked on issues #10 or #11:
 bite redmine -c ruby search --blocked 10,11
+
Values are taken from standard input when `-`.

*-R, --relates [<ID>[,...]]*::
    Restrict by relations.
+
With no argument, all matches with relations are returned. If the value is
`true` or `false`, all matches with or without relations are returned,
respectively.
+
.Search for ruby issues with relations:
 bite redmine -c ruby search --relates
+
.Search for ruby issues without relations:
 bite redmine -c ruby search --relates false
+
Regular values search for matching relations and multiple values can be
specified in a comma-separated list, matching if any of the specified
relations match.
+
.Search for ruby issues related to issue #10:
 bite redmine -c ruby search --relates 10
+
.Search for ruby issues related to issues #10 or #11:
 bite redmine -c ruby search --relates 10,11
+
Values are taken from standard input when `-`.

*--id*::
    Restrict by ID.
+
Values search for matching issue IDs and multiple values can be
specified in a comma-separated list, matching if any of the specified
IDs match.
+
Values are taken from standard input when `-`.

*-s, --status*::
    Restrict by status.
+
Query issue status from the following options: open, closed, and all.

== Time options

// TODO: include external doc describing time value format

*-c, --created*::
    Restrict by creation time.

*-u, --updated*::
    Restrict by update time.

*-c, --closed*::
    Restrict by closed time.

== Arguments

*[<terms>]*::
    Strings to search for in the subject.
+
Taken from standard input when `-`.
+
.Search for ruby issues with `test` in the subject:
 bite redmine -c ruby search test

== See Also

linkcmd:bite-redmine[1]
