include::include/header.adoc[]

== Name

bite-bugzilla - Bugzilla service support

== Synopsis

*bite bugzilla* [<options>] <command> [<args>]::
    Run a bugzilla subcommand.

*bite bugzilla* [-h|--help]::
    Output help information.

== Description

Bugzilla service support.

== Options

*-v, --verbose*::
    Increase logging verbosity.

*-q, --quiet*::
    Decrease logging verbosity.

*-h, --help*::
    Print help output and exit.

== Authentication

*-k, --key*::
	Set the API key for service access.

*-u, --user*::
	Set the username for service access.

*-p, --password*::
	Set the password for service access.

== Environment variables

*BUGBITE_KEY*::
	Set the API key for service access.

*BUGBITE_USER*::
	Set the username for service access.

*BUGBITE_PASS*::
	Set the password for service access.

== Subcommands

linkcmd:bite-bugzilla-comment[1]::
	get bug comments

linkcmd:bite-bugzilla-create[1]::
	create bug

linkcmd:bite-bugzilla-get[1]::
	get bugs

linkcmd:bite-bugzilla-history[1]::
	get bug changes

== See Also

linkcmd:bite[1]
