include::include/header.adoc[]

== Name

bite - a command line tool for bug, issue, and ticket mangling

== Synopsis

*bite* [<options>] <subcommand> [<args>]::
    Run a subcommand.

*bite* [-h|--help|-V|--version]::
    Output help or version information.

== Description

Bite is a command line tool for interacting with bug, issue, and ticket
trackers. It aims to support common actions such as searching, requesting,
creating, and updating bugs, issues, or tickets in addition to other
functionality provided by a service.

include::include/global-options.adoc[]

== Options

*-V, --version*::
    Print version and exit.

== Environment variables

*BUGBITE_CONNECTION*::
    Define a service connection to use.

== Subcommands

linkcmd:bite-bugzilla[1]::
    bugzilla service support

linkcmd:bite-github[1]::
    github service support

linkcmd:bite-redmine[1]::
    redmine service support

linkcmd:bite-show[1]::
    show service information

== Resources

*Project web site:* https://github.com/radhermit/bugbite
