include::include/header.adoc[]

== Name

bite-bugzilla-search - search bugs

== Synopsis

*bite bugzilla <search|s>* [<options>] [<terms>]::
    Search bugs.

*bite bugzilla <search|s>* [-h|--help]::
    Output help information.

== Description

Search bugs.

include::include/global-options.adoc[]

== Search options

*-b, --browser*::
    Open in a browser.
+
This uses `$BROWSER` to open URLs, falling back to `xdg-open` if undefined.

*-n, --dry-run*::
    Skip service interaction.

*--json*::
    Output in JSON format.

*--from <path>*::
    Read search attributes from a template.
+
Template files use the TOML format and generally map long option names to values.
+
Explicitly specified options override corresponding template values.

*--to <path>*::
    Write search attributes to a template.
+
Combining with `-n/--dry-run` allows creating templates without service interaction.
+
.Create a template:
 bite bugzilla -c gentoo search -c 1d -n --to template.toml

== Query options

*-f, --fields <field[,...]>*::
    Restrict the data fields returned by the query.
+
By default, only the id and subject fields are returned. This can be altered by
specifying a custom list of comma-separated field while will change the output
format to a space-separated list of the field values.
+
Group fields relate to groups of bug fields and are most useful when using JSON
formatted output:
+
.Return all bugs created in the past day rendered in JSON:
 bite bugzilla -c gentoo search --created 1d -f all --json
+
// TODO: link to rust docs for field descriptions
Possible group fields: all, default, extra, custom
+
Possible bug fields: alias, assignee, blocks, cc, component, created, creator
deadline, depends, duplicate-of, flags, id, keywords, os, platform, priority,
product, qa, resolution, see-also, severity, status, summary, tags, target,
updated, url, version, whiteboard

*-l, --limit <value>*::
    Limit the number of results.
+
If the value is higher than the maximum service limit that value is used
instead. If the limit is set to zero, all matching results are returned.

*-o, --order <field[,...]>*::
    Order the query results.
+
Fields can be prefixed with `-` or `+` to sort in descending or ascending
order, respectively. Unprefixed fields will use ascending order.
+
Multiple fields are supported via comma-separated lists which sort by each
field in order.
+
Note that if an invalid sorting request is made, sorting will fallback to the
service default.
+
Ordering is especially useful in combination with -l/--limit to get the first
or last results of an ordered match.
+
.Top ten by votes:
 bite bugzilla -c gentoo search --limit 10 --order=-votes
+
.Highest comment count:
 bite bugzilla -c gentoo search --limit 1 --order=-comments
+
// TODO: link to rust docs for field descriptions
Possible values: alias, assignee, blocks, comments, component, created,
deadline, depends, flags, id, keywords, last-visit, os, platform, priority,
product, qa, reporter, resolution, severity, status, summary, tags, target,
updated, url, version, votes, whiteboard

*-S, --quicksearch <query>*::
    Search for bugs using quicksearch syntax.

== Attribute options

*-A, --alias* <value[,...]>::
    Restrict by alias.
+
With no argument, all bugs with aliases are returned. If the value is `true` or
`false`, all bugs with or without aliases are returned, respectively.
+
.With aliases:
 bite bugzilla -c gentoo search --alias
+
.Without aliases:
 bite bugzilla -c gentoo search --alias false
+
Regular values search for matching substrings and multiple values can be
specified in a comma-separated list for logical AND or multiple options for
logical OR. Values can also use match operators to alter their query
application. See the <<Match Operators>> section for more information.
+
.Contains `value`:
 bite bugzilla -c gentoo search --alias value
+
.Contains `value1` and `value2`:
 bite bugzilla -c gentoo search --alias value1,value1
+
.Contains `value1` or `value2`:
 bite bugzilla -c gentoo search --alias value1 --alias value1

*--attachments* <value[,...]>::
    Restrict by attachments.
+
With no argument, all bugs with attachments are returned. If the value is
`true` or `false`, all bugs with or without attachments are returned,
respectively.
+
.With attachments:
 bite bugzilla -c gentoo search --attachments
+
.Without attachments:
 bite bugzilla -c gentoo search --attachments false
+
Regular string values search for matching substrings in an attachment's
description or file name. Values can also use match operators to alter their
query application. See the <<Match Operators>> section for more information.
+
Multiple values can be specified in a comma-separated list and will match if
any of the specified values match.
+
.Attachment description or file name contains `log` or `test`:
 bite bugzilla -c gentoo search --attachments log,test

*-B, --blocks* <id[,...]>::
    Restrict by blockers.
+
With no argument, all bugs with blockers are returned. If the value is `true`
or `false`, all bugs with or without blockers are returned, respectively.
+
.With blockers:
 bite bugzilla -c gentoo search --blocks
+
.Without blockers:
 bite bugzilla -c gentoo search --blocks false
+
Regular values search for matching blockers and multiple values can
be specified in a comma-separated list for logical AND or multiple
options for logical OR.
+
.Blocked on bug 10:
 bite bugzilla -c gentoo search --blocks 10
+
.Blocked on bugs 10 and 11:
 bite bugzilla -c gentoo search --blocks 10,11
+
.Blocked on bugs 10 or 11:
 bite bugzilla -c gentoo search --blocks 10 --blocks 11
+
Values can use the `-` prefix to search for non-blockers.
+
.Not blocked on bug 10:
 bite bugzilla -c gentoo search --blocks=-10
+
.Blocked on bug 10 but not bug 11:
 bite bugzilla -c gentoo search --blocks 10,-11
+
Values are taken from standard input when `-`.

*-C, --component* <value[,...]>::
    Restrict by component.
+
Values search for matching substrings or can use match operators to alter their
query application. See the <<Match Operators>> section for more information.
+
Multiple values can be specified in a comma-separated list for logical OR.

*--cf <name> <value>*::
    Restrict by custom field.
+
Values search for matching substrings or can use match operators to alter their
query application. See the <<Match Operators>> section for more information.

*-D, --depends* <id[,...]>::
    Restrict by dependencies.
+
With no argument, all bugs with dependencies are returned. If the value is
`true` or `false`, all bugs with or without dependencies are returned,
respectively.
+
.With dependencies:
 bite bugzilla -c gentoo search --depends
+
.Without dependencies:
 bite bugzilla -c gentoo search --depends false
+
Regular values search for matching dependencies and multiple values can be
specified in a comma-separated list for logical AND or multiple options for
logical OR.
+
.Depends on bug 10:
 bite bugzilla -c gentoo search --depends 10
+
.Depends on bugs 10 and 11:
 bite bugzilla -c gentoo search --depends 10,11
+
.Depends on bugs 10 or 11:
 bite bugzilla -c gentoo search --depends 10 --depends 11
+
Values can use the `-` prefix to search for non-dependencies.
+
.Doesn't depend on bug 10:
 bite bugzilla -c gentoo search --depends=-10
+
.Depends on bug 10 but not 11:
 bite bugzilla -c gentoo search --depends 10,-11
+
Values are taken from standard input when `-`.

*-F, --flags* <value[,...]>::
    Restrict by flag.
+
With no argument, all bugs with flags are returned. If the value is `true` or
`false`, all bugs with or without flags are returned, respectively.
+
.With flags:
 bite bugzilla -c gentoo search --flags
+
.Without flags:
 bite bugzilla -c gentoo search --flags false
+
Regular values search for matching substrings and multiple values can be
specified in a comma-separated list for logical AND or multiple options for
logical OR. Values can also use match operators to alter their query
application. See the <<Match Operators>> section for more information.
+
.Contains `value`:
 bite bugzilla -c gentoo search --flags value
+
.Contains `value1` and `value2`:
 bite bugzilla -c gentoo search --flags value1,value1
+
.Contains `value1` or `value2`:
 bite bugzilla -c gentoo search --flags value1 --flags value1

*-g, --groups* <value[,...]>::
    Restrict by group.
+
With no argument, all bugs with groups are returned. If the value is `true` or
`false`, all bugs with or without groups are returned, respectively.
+
.With groups:
 bite bugzilla -c gentoo search --groups
+
.Without groups:
 bite bugzilla -c gentoo search --groups false
+
Regular values search for matching substrings and multiple values can be
specified in a comma-separated list for logical AND or multiple options for
logical OR. Values can also use match operators to alter their query
application. See the <<Match Operators>> section for more information.
+
.Contains `value`:
 bite bugzilla -c gentoo search --groups value
+
.Contains `value1` and `value2`:
 bite bugzilla -c gentoo search --groups value1,value1
+
.Contains `value1` or `value2`:
 bite bugzilla -c gentoo search --groups value1 --groups value1

*--id* <id[,...]>::
    Restrict by ID.
+
Regular values search for exact bug identifiers.
+
.Equal to 10:
 bite bugzilla -c gentoo search --id 10
+
Values can use the `-` prefix to search for identifiers not equal to the value.
+
.Not equal to 10:
 bite bugzilla -c gentoo search --id=-10
+
Multiple values can be specified in a comma-separated list for logical OR.
+
.Bugs 10 or 20:
 bite bugzilla -c gentoo search --id 10,20
+
Range values are supported, (see sections <<Range Operators>> and <<Ranges>>
for more information, and values are taken from standard input when `-`.
+
.IDs greater than or equal to 10:
 bite bugzilla -c gentoo search --id '>=10'
+
.IDs between 10 and 20:
 bite bugzilla -c gentoo search --id 10..20
+
.Any ID matching values taken from a file:
 cat file | bite bugzilla -c gentoo search --id -

*-k, --keywords* <value[,...]>::
    Restrict by keyword.
+
With no argument, all bugs with keywords are returned. If the value is `true`
or `false`, all bugs with or without keywords are returned, respectively.
+
.With keywords:
 bite bugzilla -c gentoo search --keywords
+
.Without keywords:
 bite bugzilla -c gentoo search --keywords false
+
Regular values search for matching substrings and multiple values can be
specified in a comma-separated list for logical AND or multiple options for
logical OR. Values can also use match operators to alter their query
application. See the <<Match Operators>> section for more information.
+
.Contains `value`:
 bite bugzilla -c gentoo search --keywords value
+
.Contains `value1` and `value2`:
 bite bugzilla -c gentoo search --keywords value1,value1
+
.Contains `value1` or `value2`:
 bite bugzilla -c gentoo search --keywords value1 --keywords value1

*--os* <value[,...]>::
    Restrict by operating system.
+
Values search for matching substrings or can use match operators to alter their
query application. See the <<Match Operators>> section for more information.
+
Multiple values can be specified in a comma-separated list for logical OR.

*--platform* <value[,...]>::
    Restrict by platform.
+
Values search for matching substrings or can use match operators to alter their
query application. See the <<Match Operators>> section for more information.
+
Multiple values can be specified in a comma-separated list for logical OR.

*--priority* <value[,...]>::
    Restrict by priority.
+
Values search for matching substrings or can use match operators to alter their
query application. See the <<Match Operators>> section for more information.
+
Multiple values can be specified in a comma-separated list for logical OR.

*-p, --product* <value[,...]>::
    Restrict by product.
+
Values search for matching substrings or can use match operators to alter their
query application. See the <<Match Operators>> section for more information.
+
Multiple values can be specified in a comma-separated list for logical OR.

*-r, --resolution* <value[,...]>::
    Restrict by resolution.
+
Values search for matching substrings or can use match operators to alter their
query application. See the <<Match Operators>> section for more information.
+
Multiple values can be specified in a comma-separated list for logical OR.

*-U, --see-also* <value[,...]>::
    Restrict by tracker URLs.
+
With no argument, all bugs with tracker URLs are returned. If the value is
`true` or `false`, all bugs with or without tracker URLs are returned,
respectively.
+
.With tracker URLs:
 bite bugzilla -c gentoo search --see-also
+
.Without tracker URLs:
 bite bugzilla -c gentoo search --see-also false
+
Regular values search for matching substrings and multiple values can be
specified in a comma-separated list for logical AND or multiple options for
logical OR. Values can also use match operators to alter their query
application. See the <<Match Operators>> section for more information.

*--severity* <value[,...]>::
    Restrict by severity.
+
Values search for matching substrings or can use match operators to alter their
query application. See the <<Match Operators>> section for more information.
+
Multiple values can be specified in a comma-separated list for logical OR.

*-s, --status* <value[,...]>::
    Restrict by status.
+
By default, searches with no status parameter only target open bugs. This
option supports extending searches to closed bugs.
+
Regular values search for case-insensitive matches. The prefix `!` can be used
to search for all non-matches instead.
+
.Unconfirmed bugs:
 bite bugzilla -c gentoo search --status unconfirmed
+
.Unresolved bugs:
 bite bugzilla -c gentoo search --status '!resolved'
+
Multiple values can be specified in a comma-separated list for logical OR.
+
.Confirmed or verified bugs:
 bite bugzilla -c gentoo search --status confirmed,verified
+
The aliases `@open`, `@closed`, and `@all` can be used to search for open,
closed, and all bugs, respectively.
+
.Closed bugs with bugbite in the summary:
 bite bugzilla -c gentoo search --status @closed bugbite
+
.All bugs assigned to yourself:
 bite bugzilla -c gentoo search --status @all --assignee @me

*-t, --tags* <value[,...]>::
    Restrict by personal tags.
+
With no argument, all bugs with personal tags are returned. If the value is
`true` or `false`, all bugs with or without personal tags are returned,
respectively.
+
.With personal tags:
 bite bugzilla -c gentoo search --tags
+
.Without personal tags:
 bite bugzilla -c gentoo search --tags false
+
Regular values search for matching substrings and multiple values can be
specified in a comma-separated list for logical AND or multiple options for
logical OR. Values can also use match operators to alter their query
application. See the <<Match Operators>> section for more information.

*-T, --target* <value[,...]>::
    Restrict by target milestone.
+
Values search for matching substrings or can use match operators to alter their
query application. See the <<Match Operators>> section for more information.
+
Multiple values can be specified in a comma-separated list for logical OR.

*--url* <value[,...]>::
    Restrict by URL.
+
With no argument, all bugs with a URL are returned. If the value is `true` or
`false`, all bugs with or without URLs are returned, respectively.
+
.With URL:
 bite bugzilla -c gentoo search --url
+
.Without URL:
 bite bugzilla -c gentoo search --url false
+
Regular values search for matching substrings and multiple values can be
specified in a comma-separated list for logical AND or multiple options for
logical OR. Values can also use match operators to alter their query
application. See the <<Match Operators>> section for more information.

*-V, --version* <value[,...]>::
    Restrict by version.
+
Values search for matching substrings or can use match operators to alter their
query application. See the <<Match Operators>> section for more information.
+
Multiple values can be specified in a comma-separated list for logical OR.

*-w, --whiteboard* <value[,...]>::
    Restrict by whiteboard.
+
With no argument, all bugs with whiteboard info are returned. If the value is
`true` or `false`, all bugs with or without whiteboard info are returned,
respectively.
+
.With whiteboard:
 bite bugzilla -c gentoo search --whiteboard
+
.Without whiteboard:
 bite bugzilla -c gentoo search --whiteboard false
+
Regular values search for matching substrings and multiple values can be
specified in a comma-separated list for logical AND or multiple options for
logical OR. Values can also use match operators to alter their query
application. See the <<Match Operators>> section for more information.

== Attachment options

*--attachment-description* <value[,...]>::
    Restrict by attachment description.
+
Values search for matching substrings and multiple values can be specified in a
comma-separated list for logical AND or multiple options for logical OR. Match
operators can also be used alter query application, see the <<Match Operators>>
section for more information.

*--attachment-filename* <value[,...]>::
    Restrict by attachment file name.
+
Values search for matching substrings and multiple values can be specified in a
comma-separated list for logical AND or multiple options for logical OR. Match
operators can also be used alter query application, see the <<Match Operators>>
section for more information.

*--attachment-mime* <value[,...]>::
    Restrict by attachment MIME type.
+
Values search for matching substrings and multiple values can be specified in a
comma-separated list for logical AND or multiple options for logical OR. Match
operators can also be used alter query application, see the <<Match Operators>>
section for more information.

*--attachment-is-obsolete* [<bool>]::
    Restrict by attachment obsolete status.

*--attachment-is-patch* [<bool>]::
    Restrict by attachment patch status.

*--attachment-is-private* [<bool>]::
    Restrict by attachment private status.

== Range options

*--comments* <value>::
    Restrict by the number of comments.
+
Values can either be numbers, numbers prefixed with operators (see section
<<Range Operators>>), or ranges (see section <<Ranges>>).
+
Note that a bug's description is counted as a comment, but does not increment
the overall comment count shown by the `get` or `comment` subcommands.
+
.Exactly ten comments:
 bite bugzilla -c gentoo search --comments 10
+
.At least ten comments:
 bite bugzilla -c gentoo search --comments '>=10'
+
.Between five and ten comments:
 bite bugzilla -c gentoo search --comments 5..10

*--votes* <value>::
    Restrict by the number of votes.
+
Values can either be numbers, numbers prefixed with operators (see section
<<Range Operators>>), or ranges (see section <<Ranges>>).
+
Note that a bug's description is counted as a comment, but does not increment
the overall comment count shown by the `get` or `comment` subcommands.
+
.Exactly ten votes:
 bite bugzilla -c gentoo search --votes 10
 bite bugzilla -c gentoo search --votes '=10'
+
.At least ten votes:
 bite bugzilla -c gentoo search --votes '>=10'
+
.Between five and ten votes:
 bite bugzilla -c gentoo search --votes 5..10

== Change options

// TODO: list possible change fields

*--changed* <field[,...][=time]>::
    Restrict by fields changed within a time interval.
+
By default, this will match any change to the specified fields if no time interval is
given.
+
.Summary has been changed:
 bite bugzilla -c gentoo search --changed summary
+
.Summary changed in the last week:
 bite bugzilla -c gentoo search --changed summary=1w
+
.Summary changed in 2020 or later:
 bite bugzilla -c gentoo search --changed summary=2020
 bite bugzilla -c gentoo search --changed summary='>2020'
 bite bugzilla -c gentoo search --changed summary='2020..'
+
.Summary changed before 2020:
 bite bugzilla -c gentoo search --changed summary='<2020'
 bite bugzilla -c gentoo search --changed summary='..2020'
+
.Summary changed between 2020 and 2022:
 bite bugzilla -c gentoo search --changed summary='2020..2022'

*--changed-by* <field[,...]=user[,...]>::
    Restrict by fields changed by a given user.

*--changed-from* <field> <value>::
    Restrict by fields changed from a given value.

*--changed-to* <field> <value>::
    Restrict by fields changed to a given value.

== Time options

// TODO: include external doc describing time value format

*-c, --created* <time>::
    Restrict by creation time.

*-u, --updated* <time>::
    Restrict by update time.

== User Options

All user-related options search for matching substrings in login IDs by
default. Multiple values are also supported in a comma-separated list for
logical AND or multiple options for logical OR. Match operators may also be
used to alter query application, see the <<Match Operators>> section for more
information.

In addition, the alias `@me` is supported if a user account is specified for the
current service connection.

*-a, --assignee* <user[,...]>::
    Restrict by assignee user.
+
.All bugs assigned to yourself:
 bite bugzilla -c gentoo search --assignee @me

*--attacher* <user[,...]>::
    Restrict by attachment creation user.

*--cc* [<user[,...]>]::
    Restrict by CC user.
+
With no argument, all bugs with CC users are returned. If the value is `true`
or `false`, all bugs with or without CC users are returned, respectively.
+
.With CC:
 bite bugzilla -c gentoo search --cc
+
.Without CC:
 bite bugzilla -c gentoo search --cc false
+
See the information above in the <<User Options>> section for regular values.

*--commenter* <user[,...]>::
    Restrict by commenting user.

*--flagger* <user[,...]>::
    Restrict by flag creation user.

*--qa* [<user[,...]>]::
    Restrict by QA contact user.
+
With no argument, all bugs with QA contacts are returned. If the value is
`true` or `false`, all bugs with or without QA contacts are returned,
respectively.
+
.With QA contact:
 bite bugzilla -c gentoo search --qa
+
.Without QA contact:
 bite bugzilla -c gentoo search --qa false
+
See the information above in the <<User Options>> section for regular values.

*-R, --reporter* <user[,...]>::
    Restrict by reporting user.

== Comment options

*--comment* <term>::
    Strings to search for in the comments.
+
Taken from standard input when `-`.

*--comment-is-private* [<bool>]::
    Restrict by comment private status.

*--comment-tag* <value[,...]>::
    Restrict by comment tag.
+
Values search for matching substrings and multiple values can be specified in a
comma-separated list for logical AND or multiple options for logical OR. Match
operators can also be used alter query application, see the <<Match Operators>>
section for more information.
+
.Comments tagged as spam:
 bite bugzilla -c gentoo search --comment-tag spam

== Arguments

*[<terms>]*::
    Strings to search for in the summary.
+
Taken from standard input when `-`.
+
.Summary contains `test`:
 bite bugzilla -c gentoo search test

== Match Operators

Various restrictions can use match operators to alter a value's query
application. Values with no or unknown operators default to substring matching.

.Supported operators:
- `=~` -- contains case-sensitive substring
- `~~` -- contains case-insensitive substring
- `!~` -- doesn't contain case-insensitive substring
- `==` -- equal to value
- `!=` -- not equal to value
- `=*` -- matches regular expression
- `!*` -- doesn't match regular expression

Operators are applied as prefixes to values with a single space between,
wrapping the entire string in single quotes to avoid various shell expansion
support. See the following examples searching aliases for proper usage:

.Contains `value`:
 bite bugzilla -c gentoo search --alias '=~ value'

.Contains `value`, `VaLuE`, or other case-insensitive permutations:
 bite bugzilla -c gentoo search --alias '~~ value'

.Doesn't contain `value`, `VaLuE`, or other case-insensitive permutations:
 bite bugzilla -c gentoo search --alias '!~ value'

.Equals `value`:
 bite bugzilla -c gentoo search --alias '== value'

.Doesn't equal `value`:
 bite bugzilla -c gentoo search --alias '!= value'

.Matches regex:
 bite bugzilla -c gentoo search --alias '=* test?.+'

.Doesn't match regex:
 bite bugzilla -c gentoo search --alias '!* test?.+'

== Range Operators

.Supported operators:
- `<` -- less than
- `+<=+` -- less than or equal
- `=` -- equal
- `!=` -- not equal
- `>=` -- greater than or equal
- `>` -- greater than

== Ranges

// TODO: add examples and more in-depth range descriptions

.Supported operators:
- `..` -- non-inclusive range
- `..=` -- inclusive range

== See Also

linkcmd:bite-bugzilla[1]
