include::include/header.adoc[]

== Name

bite-bugzilla-get - get bugs

== Synopsis

*bite bugzilla get* [<options>] [<ids>]::
    Fetch and output bugs.

*bite bugzilla get* [-h|--help]::
    Output help information.

== Description

Get bugs.

== Global Options

*-v, --verbose*::
    Increase logging verbosity.

*-q, --quiet*::
    Decrease logging verbosity.

*-h, --help*::
    Print help output and exit.

== Get options

*-A, --no-attachments*::
    Disable attachments.

*-C, --no-comments*::
    Disable comments.

*-H, --no-history*::
    Disable history.

*-b, --browser*::
    Open bugs in a browser.
+
This functionality uses `xdg-open` to open URLs.

== Arguments

IDs or aliases of bugs to fetch.

Taken from standard input when `-`.

== Examples

.Get gentoo bug 123:
[source,console]
bite -c gentoo get 123

.Get gentoo bug 123 and only output field values:
[source,console]
bite -c gentoo get 123 -ACH

.Get all gentoo bugs created in the last day:
[source,console]
bite -c gentoo search -c 1d -f id | bite -c gentoo get -

== See Also

linkcmd:bite-bugzilla[1]
