include::include/header.adoc[]

== Name

bite - a command line tool for bug, issue, and ticket mangling

== Synopsis

*bite* [<options>] <subcommand> [<args>]::
    Run a subcommand.

*bite* [-h|--help|-V|--version]::
    Output help or version information.

== Description

Bite is a command line tool for interacting with bug, issue, and ticket
trackers. It aims to support common actions such as searching, requesting,
creating, and modifying bugs, issues, or tickets in addition to other
functionality provided by a service.

== Usage

Bite automatically injects service subcommands so they aren't required for
quicker, command-line entry if desired.

== Options

*-V, --version*::
    Print version and exit.

include::include/global-options.adoc[]

== Bite Options

*--config=<path>*::
    Load a config from a custom path.

*--insecure*::
    Ignore invalid service certificates when connecting.

*-t, --timeout=<seconds>*::
    Set the request timeout in seconds, defaults to 30.

== Service Options

*-c, --connection=<name>*::
    Use a pre-configured connection.

*-b, --base=<url>*::
    Specify the service URL to connect to.

*-s, --service=<type>*::
    Specify the service type to use.

== Environment variables

*BUGBITE_CONNECTION*::
    Use a pre-configured connection.
+
Connections can be defined in the user config in addition to other locations.
+
.Precendence order from lowest to highest
- internal config
- user config
- environment
- command option
- symlinked command

*BUGBITE_BASE*::
    Specify the service URL to connect to.
+
For example, a bugzilla service could use `https://bugzilla.kernel.org`.

*BUGBITE_SERVICE*::
    Specify the service type to use.
+
.Available services:
- bugzilla
- github
- redmine

== Subcommands

linkcmd:bite-bugzilla[1]::
    bugzilla service support

linkcmd:bite-redmine[1]::
    redmine service support

== Resources

*Project web site:* https://github.com/radhermit/bugbite
