include::include/header.adoc[]

== Name

bite-redmine-search - search issues

== Synopsis

*bite redmine search* [<options>]

*bite redmine search* [-h|--help]

== Description

Search issues.

== Global Options

*-v, --verbose*::
    Increase logging verbosity.

*-q, --quiet*::
    Decrease logging verbosity.

*-h, --help*::
    Print help output and exit.

== Search options

*-b, --browser*::
    Open in a browser.
+
This functionality uses `xdg-open` to open URLs.

*-n, --dry-run*::
    Skip service interaction.

*--json*::
    Output in JSON format.

*--from=<path>*::
    Read search attributes from a template.
+
Template files use the TOML format and generally map long option names to values.
+
Explicitly specified options override corresponding template values.

*--to=<path>*::
    Write search attributes to a template.
+
Combining this option with -n/--dry-run allows creating search templates
without service interaction.

== Query options

*-f, --fields=<field[,...]>*::
    Restrict the data fields returned by the query.
+
By default, only the id and subject fields are returned. This can be altered by
specifying a custom list of comma-separated field while will change the output
format to a space-separated list of the field values.
+
.Possible values:
- *assignee*: person the issue is assigned to
- *author*: person who created the issue
- *closed*: time when the issue was closed
- *created*: time when the issue was created
- *id*: issue ID
- *priority*: issue priority
- *status*: issue status
- *subject*: issue subject
- *tracker*: issue type
- *updated*: time when the issue was last updated

*-l, --limit=<value>*::
    Limit the number of results.
+
If the value is higher than the maximum limit that value is used instead and if
the limit is set to zero, the default limit is used. Note that the maximum and
default limits are generally not equal, with most instances using 100 and 25,
respectively.

*-o, --order=<field[,...]>*::
    Order the query results.
+
Fields can be prefixed with `-` or `+` to sort in descending or ascending
order, respectively. Unprefixed fields use ascending order.
+
Multiple fields can be specifying in a comma-separated list which sort the
results by each field in order.
+
If an invalid sorting request is made, the default ordering will be used.
+
.Possible values:
- *assignee*: person the issue is assigned to
- *author*: person who created the issue
- *closed*: time when the issue was closed
- *created*: time when the issue was created
- *id*: issue ID
- *priority*: issue priority
- *status*: issue status
- *subject*: issue subject
- *tracker*: issue type
- *updated*: time when the issue was last updated

== Attribute options

*-a, --assignee=[<bool>]*::
    Restrict by assignee status.
+
With no argument, all matches with assignees are returned. If the value is
`true` or `false`, all matches with or without assignees are returned,
respectively.
+
.Search for assigned ruby issues:
[source,console]
bite -c ruby search --assignee
+
.Search for unassigned ruby issues:
[source,console]
bite -c ruby search --assignee false

*--attachments=[<value>[,...]]*::
    Restrict by attachments.
+
With no argument, all matches with attachments are returned. If the
value is `true` or `false`, all matches with or without attachments
are returned, respectively.
+
Regular string values search for matching substrings in an
attachment's file name.
+
Multiple values can be specified in a comma-separated list and will
match if all of the specified values match.
+
.Search for ruby issues with attachments:
[source,console]
bite -c ruby search --attachments
+
.Search for ruby issues without attachments:
[source,console]
bite -c ruby search --attachments false
+
.Search for ruby issues with file names containing `test`:
[source,console]
bite -c ruby search --attachments test
+
.Search for ruby issues with file names containing `test` and `log`:
[source,console]
bite -c ruby search --attachments test,log

== Time options

// TODO: include external doc describing time value format

*-c, --created*::
    Restrict by creation time.

*-m, --modified*::
    Restrict by modification time.

*-c, --closed*::
    Restrict by closed time.

== See Also

linkcmd:bite-redmine[1]
