include::include/header.adoc[]

== Name

bite-bugzilla-search - search bugs

== Synopsis

*bite bugzilla search* [<options>] [<term>]::
    Search bugs.

*bite bugzilla search* [-h|--help]::
    Output help information.

== Description

Search bugs.

== Global Options

*-v, --verbose*::
    Increase logging verbosity.

*-q, --quiet*::
    Decrease logging verbosity.

*-h, --help*::
    Print help output and exit.

== Search options

*-b, --browser*::
    Open in a browser.
+
This functionality uses `xdg-open` to open URLs.

*-n, --dry-run*::
    Skip service interaction.

*--json*::
    Output in JSON format.

*--from=<path>*::
    Read search attributes from a template.
+
Template files use the TOML format and generally map long option names to values.
+
Explicitly specified options override corresponding template values.

*--to=<path>*::
    Write search attributes to a template.
+
Combining with --dry-run allows creating templates without service interaction.

== Arguments

*[<terms>]*::
    Strings to search for in the summary.
+
Taken from standard input when `-`.
+
.Search for bugs with `test` in the summary:
[source,console]
bite -c gentoo search test

== See Also

linkcmd:bite-bugzilla[1]
