include::include/header.adoc[]

== Name

bite - a command line tool for bug, issue, and ticket mangling

== Synopsis

*bite* [<options>] <subcommand> [<args>]::
    Run a subcommand.

*bite* [-h|--help|-V|--version]::
    Output help or version information.

== Description

Bite is a command line tool for interacting with bug, issue, and ticket
trackers. It aims to support common actions such as searching, requesting,
creating, and updating bugs, issues, or tickets in addition to other
functionality provided by a service.

== Usage

Bite supports multiple service variants via subcommands, providing a common
interface between them. However, specifying service commands is unnecessary as
they are auto-injected from the required connection options.

For example the quickest way to use `bite` interactively is to set the
environment variable `BUGBITE_CONNECTION` and use action aliases:

 # search for all Linux kernel bugs created in the last week
 export BUGBITE_CONNECTION=linux
 bite s -c 1w

Alternatively, the somewhat more verbose method using the connection option and
full action commands is supported as well:

 # search for all Gentoo bugs created in the past week with attachments
 bite -c gentoo search -c 1d --attachments

== Options

*-V, --version*::
    Print version and exit.

include::include/global-options.adoc[]

== Bite Options

*--config <path>*::
    Load a config from a custom path.

*--insecure*::
    Ignore invalid service certificates when connecting.

*-t, --timeout <seconds>*::
    Set the request timeout in seconds, defaults to 30.

== Service Options

*-c, --connection <name>*::
    Use a pre-configured connection.

*-b, --base <url>*::
    Specify the service URL to connect to.

*-s, --service <type>*::
    Specify the service type to use.

== Environment variables

*BUGBITE_CONNECTION*::
    Use a pre-configured connection.

*BUGBITE_BASE*::
    Specify the service URL to connect to.
+
For example, a bugzilla service could use `https://bugzilla.kernel.org`.

*BUGBITE_SERVICE*::
    Specify the service type to use.
+
.Available services:
- bugzilla
- github
- redmine

== Subcommands

linkcmd:bite-bugzilla[1]::
    bugzilla service support

linkcmd:bite-github[1]::
    github service support

linkcmd:bite-redmine[1]::
    redmine service support

== Resources

*Project web site:* https://github.com/radhermit/bugbite
