services:
  db:
    image: mariadb:12
    environment:
      MARIADB_ROOT_PASSWORD: bugzilla
      MARIADB_DATABASE: bugzilla
      MARIADB_USER: bugzilla
      MARIADB_PASSWORD: bugzilla
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 3s
      retries: 5

  bugzilla:
    image: ghcr.io/radhermit/bugbite-bugzilla:5.2.0.20260726
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
    environment:
      - BZ_ADMIN_EMAIL=bugbite@bugbite.test
      - BZ_ADMIN_PASSWORD=bugbite
      - BZ_ADMIN_REALNAME=Bugbite
      - BZ_URLBASE=http://127.0.0.1:8080/
      - BZ_DB_HOST=db
      - BZ_DB_PORT=3306
      - BZ_DB_USER=bugzilla
      - BZ_DB_NAME=bugzilla
      - BZ_DB_PASS=bugzilla
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 10s
