name: ci

on:
  push:
    branches: ['**']
    paths:
      - "Cargo.*"
      - "**/*.rs"
      - "crates/*/doc/**"
      - "crates/*/testdata/**"
      - "docker/*"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "Cargo.*"
      - "crates/*/doc/**"
      - "crates/*/src/**"

jobs:
  msrv:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.msrv.outputs.version }}
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

    - name: Get the minimum supported rust version (MSRV)
      id: msrv
      run: |
        version=$(sed -rn '/^rust-version\s*=/ s/^.*=\s*"([0-9](\.[0-9]+)+)(.*)/\1/p' Cargo.toml)
        if [[ -n ${version} ]]; then
          echo "version=${version}" >> $GITHUB_OUTPUT
        else
          exit 1
        fi

  test:
    needs: msrv
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rust-version: ${{ needs.msrv.outputs.version }}
            rust: msrv
          - os: ubuntu-latest
            rust-version: stable
            rust: stable
          - os: macos-latest
            rust-version: stable
            rust: stable

    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772
      id: rust
      with:
        toolchain: ${{ matrix.rust-version }}
        components: llvm-tools-preview

    - name: Install cargo-nextest
      uses: taiki-e/install-action@ba47c86ac325773530516bb756137ac718732518 #v2.86.5
      with:
        tool: nextest

    - name: Install grcov
      if: ${{ matrix.rust == 'stable' && runner.os == 'Linux' }}
      uses: taiki-e/install-action@ba47c86ac325773530516bb756137ac718732518 #v2.86.5
      with:
        tool: grcov

    - name: Set up rust build cache
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 #v2.9.2
      with:
        # only save cache when running on the main branch
        save-if: ${{ github.ref_name == 'main' }}

    - name: Configure build environment
      run: |
        if [[ ${{ matrix.rust }} == 'stable' && ${{ runner.os }} == 'Linux' ]]; then
          echo "RUSTFLAGS=-C instrument-coverage -C strip=symbols" >> $GITHUB_ENV
          echo "CFLAGS=-Wl,--build-id" >> $GITHUB_ENV
          echo "LLVM_PROFILE_FILE=${{ github.workspace }}/target/%b-%4m.profraw" >> $GITHUB_ENV
        else
          echo "RUSTFLAGS=-C strip=symbols" >> $GITHUB_ENV
        fi

    - name: Build tests
      run: |
        # build tests
        cargo build --all-features --workspace --tests

    - name: Run tests
      run: |
        # run unit tests
        cargo nextest run --all-features --workspace --tests

        # run integration tests
        if [[ ${{ matrix.rust }} == 'stable' && ${{ runner.os }} == 'Linux' ]]; then
          # start bugzilla service
          docker compose -f docker/bugzilla.yml up --wait
          # run tests
          cargo nextest run --all-features --profile bugzilla --workspace --tests
          # stop bugzilla service
          docker compose -f docker/bugzilla.yml down
        fi

    - name: Process code coverage
      id: coverage
      run: |
        # default to not uploading coverage
        COVERAGE=false

        # only collect coverage for the latest rust release on linux
        if [[ ${{ matrix.rust }} == 'stable' && ${{ runner.os }} == 'Linux' ]]; then
          # move all profile data respecting $LLVM_PROFILE_FILE to the expected location
          mkdir -p target/coverage
          mv target/*.profraw target/coverage

          # process coverage information
          mkdir coverage
          grcov target/coverage \
            --source-dir . --binary-path target/debug --llvm --branch \
            --keep-only "crates/*/src/*" -t html,lcov -o coverage \
            --excl-line "unreachable!(.*)|grcov-excl-line" \
            --excl-start grcov-excl-start \
            --excl-stop grcov-excl-stop

          # Manually check if coverage processing failed since grcov doesn't return a
          # failure status on error.
          #
          # See the upstream issue at https://github.com/mozilla/grcov/issues/1160.
          if [[ $(grep -c . coverage/lcov) -le 1 ]]; then
            echo "::warning:: Skipping code coverage, grcov failed processing data"
          else
            COVERAGE=true
          fi

          # error out if $LLVM_PROFILE_FILE isn't being respected by any tests
          rm -rf target/coverage
          profraw_files=$(find . -name \*.profraw)
          if [[ -n "${profraw_files}" ]]; then
            echo "Unknown profraw files: ${profraw_files}"
            exit 1
          fi
        fi

        # set output to disable uploading code coverage on grcov failure
        echo "coverage=${COVERAGE}" >> $GITHUB_OUTPUT

    - name: Upload coverage to Codecov
      if: ${{ steps.coverage.outputs.coverage == 'true' }}
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f #v7.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage/lcov
        disable_search: true
        fail_ci_if_error: false
