name: lint

on:
  push:
    branches: ['**']
    paths:
      - "**/*.rs"
      - ".github/workflows/lint.yml"
  pull_request:
    branches: [main]
    paths: "**/*.rs"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772
      id: rust
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Set up rust build cache
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 #v2.9.2
      with:
        # only save cache when running on the main branch
        save-if: ${{ github.ref_name == 'main' }}

    - name: Run rustfmt
      run: cargo fmt --check

    - name: Run clippy
      run: cargo clippy --all-features --all-targets
